sudo: required
services: 
  - docker

before_install:
  - docker build -t colinjc/docker-react -f Dockerfile.dev .

script:
  - docker run colinjc/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "S3elasticbeanstalk-us-east-1-431175250183"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"